name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0-8 * * *'
    - cron: '*/5 9-16 * * *'
    - cron: '30 17-23 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Checkout data
        uses: actions/checkout@v4
        with:
          ref: data
          path: data
          token: ${{ secrets.GH_TOKEN }}
      - name: Run
        run: python main.py ${{ secrets.BIG_GIVE_URL }} ${{ secrets.SLACK_TRIGGER_URL }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: data
